### PR TITLE
#2122 Expression builder - After expression validation, chars need to be entered twice to reflect

### PR DESCRIPTION
**Pull request by mikieyx**
Fixes: #2122 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by mikieyx** [comment]
Waiting for #2118 to merge, then I can use the updated utility files to create a unit test for the fix.

**Comment by mikieyx** [comment]
Cannot add a unit test case that tests that the cursor position is in the right spot. I believe to find the cursor position, I would need to access an instance of `expression` which RTL is unable to do.

**Comment by srikant-ch5** [comment]
Hi @mikieyx the condition which you have removed was added to resolve below issue. Could you please verify whether it is working fine ?
https://github.com/elyra-ai/canvas/issues/2066

**Comment by veenas1** [comment]
> Hi @mikieyx the condition which you have removed was added to resolve below issue. Could you please verify whether it is working fine ? #2066

@mikieyx If we remove those lines, the below scenario will not be working I guess. Can you please check?

https://github.com/user-attachments/assets/373f94ac-7107-4382-bf29-3c7b6c25e3bc

**Review by veenas1 — CHANGES_REQUESTED** [review]
please check the scenario mentioned in above comment

**Comment by mikieyx** [comment]
The scenario doesn't work with my changes. I'll make some changes so the above scenario works while also eliminating the bug.

**Comment by veenas1** [comment]
LGTM, except one scenario: Currently once the expression is edited from the editor, on closing, it is reflected in the flyout even **without** clicking Save. But with these changes, it reflects only on saving. 
@matthoward366 Is it fine?

https://github.com/user-attachments/assets/7842084e-eea6-4921-9756-be3724851114

**Comment by mikieyx** [comment]
> That is the correct behavior. We should only be saving when the user clicks `Ok`. I found 1 odd behavior. If I click cancel and try to reopen the editor I have to click the button twice. This didn't happen before.
> 
> @mikieyx can you see why this regressed?

Hey Matt, I'm not seeing that issue on my end. I'm opening up the editor, clicking cancel, and then clicking the calculator icon once, and it is opening.

**Comment by matthoward366** [comment]
Can you try entering text, then clicking cancel?

**Comment by mikieyx** [comment]
> Can you try entering text, then clicking cancel?

I tried that and I'm seeing your issue. After clicking the cancel, the cursor is still in the editor. You have to click twice, one to unfocus the cursor and then one to click on the expression builder icon. I'll look into it.

**Review by matthoward366 — APPROVED** [review]
Looks good

**Comment by veenas1** [comment]
> I tried that and I'm seeing your issue. After clicking the cancel, the cursor is still in the editor. You have to click twice, one to unfocus the cursor and then one to click on the expression builder icon. I'll look into it.

Hi @mikieyx @matthoward366  I saw similar behavior after editing in the flyout itself. Need to click the icon twice to open the editor modal.

https://github.com/user-attachments/assets/ced4e1f5-ae92-495c-b801-c43057f7ac87

**Comment by matthoward366** [comment]
@veenas1 can you create a new issue for this?

**Comment by veenas1** [comment]
[Expression Builder: After editing in flyout,user needs to click icon twice to open Editor #3897](https://github.ibm.com/NGP-TWC/wdp-abstract-canvas/issues/3897)

**Pull request merged**
