### PR TITLE
Invert colors in tearsheet container

### LINKED ISSUE #1259: Invert colors in tearsheet container
ref 3404

There is a new Tearsheet container introduced in common properties. We need to make sure all the controls displayed in the Tearsheet are inverted so that it displays nicely.

Verify dark theme as well: https://pages.github.ibm.com/cdai-design/pal/components/tearsheet/usage#light-and-dark-theming

- [x] field picker table background when filtering
- [x] tables
  - [x] structuretable
  - [x] someoneselect
  - [x] field-picker
- [x] code control

### PR DESCRIPTION
**Pull request by caritaou**
closes #1259
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by nmgokhale** [comment]
Few comments after testing -

- Still showing both `Cancel` button and `X` icon in tearsheet
- Primary tabs need to be sticky (condition_paramDef.json "Selects" tab scroll down to the end, primary tabs don't show)
- When clicked on "Edit" icon in table row, modal opens up with no left padding
Screen Shot 2022-11-28 at 4 25 44 PM

- When I change value in dropdown in table row, it shows different background for newly selected value ("date" has different background) -
Screen Shot 2022-11-28 at 4 26 49 PM

- After filtering all columns in fieldpicker table, it shows some white background -
Screen Shot 2022-11-28 at 4 31 32 PM

- When I hover over table row, hover color looks same as table header -
Screen Shot 2022-11-28 at 4 39 24 PM

- In DisplayRows_paramDef.json subpanel, there's grey background behind Add and remove rows buttons -
Screen Shot 2022-11-28 at 4 41 44 PM

- Expression control in subpanel has white background same as subpanel background -
Screen Shot 2022-11-28 at 4 44 09 PM

**Comment by caritaou** [comment]
> Still showing both Cancel button and X icon in tearsheet
> Primary tabs need to be sticky (condition_paramDef.json "Selects" tab scroll down to the end, primary tabs don't show)

These will be done in a separate issue: https://github.com/elyra-ai/canvas/issues/1278

> When clicked on "Edit" icon in table row, modal opens up with no left padding

This is the same behavior for container type Modal. Separate issue opened to fix this: https://github.com/elyra-ai/canvas/issues/1280

>When I hover over table row, hover color looks same as table header

These are using the Carbon tokens, those are actually different colors. I will double check if the correct tokens are applied here

> After filtering all columns in fieldpicker table, it shows some white background
> In DisplayRows_paramDef.json subpanel, there's grey background behind Add and remove rows buttons
> Expression control in subpanel has white background same as subpanel background
> List control doesn't have left and right borders 

Thanks for catching these, will fix in this PR

>Nested Summary panel isn't showing up correctly. Since tearsheet doesn't show summary panels, maybe this is expected?

Yes this is expected


> Truncated Sub tabs don't show tooltip

I see there is a tooltip for this, is this what you were referring to?
image

**Comment by nmgokhale** [comment]
> Truncated Sub tabs don't show tooltip

Screen Shot 2022-11-29 at 11 35 14 AM

**Comment by caritaou** [comment]
@nmgokhale 

> After filtering all columns in fieldpicker table, it shows some white background
Expression control in subpanel has white background same as subpanel background

These were previously fixed, can you try again after rebuilding common-canvas?

> In DisplayRows_paramDef.json subpanel, there's grey background behind Add and remove rows buttons
List control doesn't have left and right borders

I just pushed a fix for these

> Truncated Sub tabs don't show tooltip

You can ignore these as this problem existed before. Since we are moving to use left nav, this will change completely

**Review by nmgokhale — APPROVED** [review]

**Pull request merged**
