### PR TITLE
#2003 Open Link in Tooltip in Safari browser.

### PR DESCRIPTION
**Pull request by srikant-ch5**
Fixes: #2003 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by srikant-ch5** [comment]
Hi @nmgokhale these changes opens link in tooltip link in safari but due to [resize event](https://github.com/elyra-ai/canvas/blob/f445ddc334b092cf9c26c1c5af8f59d703f8bbff/canvas_modules/common-canvas/src/tooltip/tooltip.jsx#L40) its getting closed after clicking.

**Comment by nmgokhale** [comment]
@srikant-ch5 Please add issue number in your PR title

**Comment by nmgokhale** [comment]
@srikant-ch5 Is there any workaround to keep this code `window.addEventListener("resize", this.hideTooltipOnScrollAndResize, true);` And still tooltip remain open in Safari like it does in Chrome and Firefox?

**Comment by srikant-ch5** [comment]
> @srikant-ch5 Is there any workaround to keep this code `window.addEventListener("resize", this.hideTooltipOnScrollAndResize, true);` And still tooltip remain open in Safari like it does in Chrome and Firefox?

Hi @nmgokhale Could you please review these latest changes whether they are fine ?

**Review by nmgokhale — APPROVED** [review]

**Pull request merged**
