### PR TITLE
#1908 Added table toolbar for properties tables

### PR DESCRIPTION
**Pull request by nmgokhale**
Fixes: #1908 

- Show table toolbar when 1+ rows are selected in tables which have either Add/remove buttons, row move buttons, or multi select editable tables. 
- Table toolbar replaces table header (which has Add button and Search container). To see the Add button again, user will have to click `Cancel` button in Table toolbar to clear row selections.
- In case of multi select edit rows, `Edit` button will show up in the toolbar. Clicking on `Edit` button in table toolbar will open a subpanel where users can edit multi-select editable fields. At this time, **edit button in selected rows will be disabled**.

Screenshot 2024-05-17 at 4 23 49 PM

For list control in small flyout, show `# item` in the table toolbar -
Screenshot 2024-05-17 at 4 36 45 PM

Don't show table toolbar for **Fieldpicker** and **Expression field/function tables** because there aren't any batch actions (delete, row move) possible for these tables -
Screenshot 2024-05-17 at 4 38 05 PM
Screenshot 2024-05-17 at 4 38 22 PM

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by caritaou — DISMISSED** [review]
Looks good!

**Comment by matthoward366** [comment]
In type.json if I select 2 rows I see this error
```
editor-form.jsx:345 Uncaught TypeError: Cannot read properties of undefined (reading 'itemType')
    at EditorForm.genUIItem (editor-form.jsx:345:1)
    at StructureTableControl.buildMultiSelectEditChildItem (abstract-table.jsx:779:1)
    at StructureTableControl.makeTableToolbar (abstract-table.jsx:439:1)
    at StructureTableControl.createTable (abstract-table.jsx:610:1)
    at StructureTableControl.render (structuretable.jsx:165:1)
    at finishClassComponent (react-dom.development.js:19752:1)
    at updateClassComponent (react-dom.development.js:19698:1)
    at beginWork (react-dom.development.js:21611:1)
    at HTMLUnknownElement.callCallback (react-dom.devel
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
```

type-issue

**Comment by nmgokhale** [comment]
[type.json](https://github.com/elyra-ai/canvas/blob/main/canvas_modules/harness/test_resources/forms/type.json) is using old schema. It doesn't have `complex_types` section which is causing above error.
Screenshot 2024-05-22 at 2 27 36 PM


I copied the `Type` node code from wml-canvas-runtimes repo into this JSON file - 
[type_node_paramDef.json](https://github.com/elyra-ai/canvas/files/15409266/type_node_paramDef.json)

This is showing Edit button in toolbar when multiple rows are selected.
Screenshot 2024-05-22 at 3 28 46 PM


`Values` column has `edit_style: "inline"` but it's a readonly control. I added an extra check to not show readonly controls in MSE subpanel. Because readonly column is not supposed to be edited.

**Review by matthoward366 — APPROVED** [review]
Looks good

**Pull request merged**
