### PR TITLE
#924 replace moment with new date formatting module

### PR DESCRIPTION
**Pull request by matthoward366**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

issue #924

### CODE REVIEW

**Comment by nmgokhale** [comment]
Error message should be updated to `MM/DD/YYYY` because single digit date and month aren't valid anymore.
Screen Shot 2022-01-31 at 11 16 34 AM

If I enter the date as `1/5/2021` in the table and save. When I open the table again, date is changed to `2021-00-05` - 
Screen Shot 2022-01-31 at 11 18 22 AM

**Comment by nmgokhale** [comment]
This is a minor change but dates in tooltips no longer match with the dates in fields -
Screen Shot 2022-01-31 at 11 22 58 AM

**Comment by nmgokhale** [comment]
Timestamp field in table - Day missing. 
Screen Shot 2022-01-31 at 11 55 13 AM

**Comment by matthoward366** [comment]
> Error message should be updated to MM/DD/YYYY because single digit date and month aren't valid anymore.
single digit dates are valid.  

>Same for Error message in Timefield control. H:m:s no longer valid -
Same as above.  `1` isn't valid since you still need m and s.  

>If I enter the date as 1/5/2021 in the table and save. When I open the table again, date is changed to 2021-00-05 -
Good catch.  Fixed.

>If I enter time as 1:5:10 and save. Time is changed to 01:05:10:-08:00
Good catch.  Fixed

>This is a minor change but dates in tooltips no longer match with the dates in fields -
This is the same as what's in the code today.  We don't format the date/time in tooltips.  We can create a new issue to track that.

>Timestamp field in table - Day missing.
This is expected.  It was changed in table cells to reduce the string length.

**Review by nmgokhale — APPROVED** [review]

**Pull request merged**
