### PR TITLE
#1635 Highlighting of radio buttons cut off when radio button is clicked

### PR DESCRIPTION
**Pull request by veenas1**
Fixes: #1635
When radio buttons are selected they appear with part of the circle cut off

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by matthoward366** [comment]
One issue with adding the padding is now the alignment is off.
Screenshot 2023-12-01 at 4 40 34 PM

**Comment by veenas1** [comment]
@matthoward366 What I can think of is adding a padding for the label as well, but it could cause alignment issues in other places of the app as it is a common reused label. As discussed, better we may park this till we upgrade to Carbon 11.

**Comment by matthoward366** [comment]
I agree.  Let's wait until we update to carbon 11.

**Comment by veenas1** [comment]
Closing this, created New PR #1814.
Will replace the custom code for grouping with carbon's `RadioButtonGroup`.

**Pull request closed without merging**
