### PR TITLE
Prepare test harness for demo

### PR DESCRIPTION
**Pull request by nmgokhale**
1. Double clicking nodes in `Flows` opens node properties 
Screenshot 2023-04-20 at 4 50 11 PM

2. Added `Dates, Toggle, Tab and SubTab` sections and removed `Configure derive node` section
Screenshot 2023-04-20 at 4 25 16 PM

3. Basic JSON file for demo -
Screenshot 2023-04-27 at 9 58 28 AM

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by nmgokhale** [comment]
Changing `JavaScript_FilterRows_paramDef.json` to add `Colors` radio button for demo

**Review by matthoward366 — APPROVED** [review]
lgtm

**Review by tomlyn — CHANGES_REQUESTED** [review]
The idea of the sample apps is that they are simple apps that a developer can look at to find out how common-canvas works. This properties code makes this particular sample app quite big. therefore, is it possible for this properties code to be refactored into a wrapper class for `<CommonProperties>` ?

**Comment by nmgokhale** [comment]
I will create a `flows-properties.jsx` file and move all the new code from `flows-canvas.jsx` into new file.

**Review by tomlyn — DISMISSED** [review]
Looks great

**Comment by nmgokhale** [comment]
PR ready for review. Travis build fixed and `basicCommonProperties_paramDef` updated as per demo feedback -
Screenshot 2023-04-27 at 9 58 28 AM

**Review by caritaou — APPROVED** [review]

**Pull request merged**
