### PR TITLE
Add link label editing feature.

### PR DESCRIPTION
**Pull request by JuanKUYang**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by JuanKUYang** [comment]
This PR is for issue https://github.ibm.com/NGP-TWC/wdp-abstract-canvas/issues/3131

**Comment by JuanKUYang** [comment]
Hi @vlad-bunescu, could you please review my code changes for this PR? Thanks!

**Comment by JuanKUYang** [comment]
This PR is for issue https://github.com/elyra-ai/community/issues/9.

**Comment by JuanKUYang** [comment]
This PR is for issue https://github.com/elyra-ai/canvas/issues/657.

**Comment by tomlyn** [comment]
@JuanKUYang Thanks for attempting to implement this issue.  I looked through your changes and they didn't really implement the feature the way I wanted with respect to the current architecture.  I had previously worked on this feature myself so I've gone ahead and completed the work I'd already started and implemented it in a separate PR.
So I am closing this PR. Thanks for your efforts on this.

**Pull request closed without merging**
