### PR TITLE
#1758 : Typo in Readme

### PR DESCRIPTION
**Pull request by srikant-ch5**
Fixes : #1758
Fix Typo in mkdocs instructions in Readme and add comment to remove NODE_OPTIONS in test harness package.json.
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by srikant-ch5** [comment]
Hi @matthoward366 we can also edit the documentation by clicking on below icon. Should this instruction be mentioned in Readme ?
Screenshot 2024-03-21 at 6 51 58 PM

**Comment by matthoward366** [comment]
I don't think so.  How does this even work?  Would that update the code somehow?

**Review by matthoward366 — APPROVED** [review]

**Comment by srikant-ch5** [comment]
> I don't think so. How does this even work? Would that update the code somehow?

Hi @matthoward366 When we click on that icon. It shows below message saying the changes will be saved to a new branch in our fork and using it we can raise a PR.
Screenshot 2024-03-22 at 12 07 52 PM

**Comment by matthoward366** [comment]
Can we hide the icon?

**Comment by srikant-ch5** [comment]
> Can we hide the icon?

Sure I will look into this.

**Pull request merged**
