### PR TITLE
#2235 Rtl panel migration-Part1

### PR DESCRIPTION
**Pull request by Jerinjk14**
Fixes: #2235  
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by nmgokhale** [comment]
@Jerinjk14 Please follow these steps for this and future PRs -

- Create a new issue here - https://github.com/elyra-ai/canvas/issues
- Add `ref: wdp-abstract-canvas issue number` in the new issue. You can see how its done in existing issues
- PR title should start with `elyra-canvas-issue-number`
- [PR description](https://github.com/elyra-ai/canvas/pull/2217#issue-2603053691) should have `fixes: elyra-canvas-issue-number`

**Comment by nmgokhale** [comment]
Is there going to be a separate PR for [remaining files in panels](https://github.com/elyra-ai/canvas/tree/main/canvas_modules/common-canvas/__tests__/common-properties/panels)?

**Comment by Jerinjk14** [comment]
@nmgokhale , yes Panels containing more than 10 files, so will raise a new PR for the others

**Comment by nmgokhale** [comment]
@Jerinjk14 Please update your PR following the steps given here - https://github.com/elyra-ai/canvas/pull/2217#issuecomment-2442872347

**Comment by Jerinjk14** [comment]
@nmgokhale , Created new issue in elyra-ai/canvas and updated as per your comments, kindly check now

**Review by nmgokhale — APPROVED** [review]

**Pull request merged**
