### PR TITLE
#1044 Draggable border in script panel is too thick

### PR DESCRIPTION
**Pull request by nabilIbm**
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by matthoward366** [comment]
Screen Shot 2022-05-04 at 7 39 33 AM

There seems like something wrong with the borders yet.  There is a gap between the bottom-panel-drag and top border of bottom-panel.

**Comment by nabilIbm** [comment]
@matthoward366 Can you please check
default case :
image
Hover case :
image

**Comment by matthoward366** [comment]
Screen Shot 2022-05-04 at 10 25 30 AM

The border is still too thick.  You setting it to white which is hiding how thick it actually is.

**Comment by tomlyn** [comment]
@matthoward366 Regarding the border width. If the div is sized to be only one pixel width it makes the "hover over" area quite small which makes it difficult for the user to get the mouse pointer to change to the sizing cursor. So making part of the div width that is colored like the panel seems reasonable - no?

**Comment by matthoward366** [comment]
We don't know the color of the bottom panel since consumers can make the content whatever they want.  In some cases it might not be white which would look odd.

**Comment by matthoward366** [comment]
I think we are good on the using the same color for the background and leaving the draggable div.  We just need to update it to use the token instead.

**Review by matthoward366 — APPROVED** [review]
lgtm

**Pull request merged**
