### PR TITLE
#2112 Title action buttons style updates

### LINKED ISSUE #2112: Title action buttons style updates
ref planning 7169

Action buttons in the title will only take 50% width if displayed in the small right flyout and the text will be overflow into ellipsis if too long. In all other flyout widths, we will use the default sizing of Carbon buttons
image

### PR DESCRIPTION
**Pull request by caritaou**
closes #2112 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by caritaou** [comment]
Small right flyout:
image

expands to flow freely:
image

**Comment by srikant-ch5** [comment]
Hi @caritaou I increased `Decrement` text length and can see the text overflows outside the button, please refer below recording.


https://github.com/user-attachments/assets/bea2e93a-0a2b-46f0-96d5-2c16076c975a

**Comment by caritaou** [comment]
Hi @srikant-ch5, that is the same behavior on Carbon buttons. It'll be up to the consumers to use a reasonable label for the buttons so that it does not extend past the max length of a button (320px). I only modified the overflow of a button for the small width right flyout since we need to adjust them to fit within the tight space. Everything else will be done with the standard Carbon button specs to layout as is

**Review by srikant-ch5 — APPROVED** [review]

**Review by srikant-ch5 — APPROVED** [review]

**Review by tomlyn — APPROVED** [review]
LGTM

**Pull request merged**
